# Generated by Django 5.0.6 on 2025-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_yearscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='points',
        ),
        migrations.AddField(
            model_name='yearscore',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
