# Generated by Django 5.0.6 on 2025-04-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_friendrequest_friendrequest_unique_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='amount_p_guessed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='amount_p_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
