# Generated by Django 5.0.6 on 2025-04-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_amount_p_guessed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='amount_p_guessed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='amount_p_wrong',
        ),
    ]
