# Generated by Django 5.2 on 2025-06-04 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=2025)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('position', models.IntegerField(default=0)),
                ('gps_participated', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', 'user__username'],
            },
        ),
    ]
