# Generated by Django 5.0.6 on 2025-04-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearscore',
            name='last_position',
            field=models.IntegerField(default=0),
        ),
    ]
