# Generated by Django 5.0.6 on 2025-04-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_yearscore_last_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearscore',
            old_name='last_position',
            new_name='position',
        ),
    ]
