# Generated by Django 5.2 on 2025-05-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_alter_yearscore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearscore',
            name='gps_participated',
            field=models.IntegerField(default=0),
        ),
    ]
