# Generated by Django 5.2 on 2025-05-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_yearscore_gps_participated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearscore',
            old_name='year',
            new_name='season',
        ),
    ]
